# Form implementation generated from reading ui file 'UI/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 676)
        MainWindow.setStyleSheet(
            "#mainWidget{\n"
            "    background-color: #F0F0F0;\n"
            "}\n"
            "#slidersFrame{\n"
            "    background-color: #f5f5f5;\n"
            "}\n"
            "#leftFrame{\n"
            "    background-color: #f5f5f5;\n"
            "}\n"
            "QPushButton{\n"
            "  background-color: #333333;\n"
            "  border: none;\n"
            "  border-radius: 6px;\n"
            "  color: #cccccc;\n"
            "  font-size: 14px;\n"
            "  font-weight: 500;\n"
            "  line-height: 20px;\n"
            "  list-style: none;\n"
            "  padding: 4px 12px;\n"
            "  height:40px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    background-color: rgba(51, 51, 51, 0.5);\n"
            "     text-decoration: none;\n"
            "}\n"
            "QPushButton:focus{\n"
            "     outline: 1px transparent;\n"
            "}\n"
            "QLabel{\n"
            "    font-weight: bold;\n"
            "    font-size: 16px;\n"
            "}\n"
            "QGroupBox{\n"
            "    font-weight: bold;\n"
            "    font-size: 16px;\n"
            "    padding:30px 0px 0px 0px;\n"
            "    border:none;\n"
            "}\n"
            "QLineEdit{\n"
            "    border:none;\n"
            "    padding:4px 10px;\n"
            "    border-radius: 3px;\n"
            "}\n"
            "QListWidget{\n"
            "    border:none;\n"
            "    border-radius: 3px;\n"
            "}\n"
            "QSlider::groove:horizontal {\n"
            "border: 1px solid #bbb;\n"
            "background: white;\n"
            "height: 10px;\n"
            "border-radius: 4px;\n"
            "}\n"
            "\n"
            "QSlider::sub-page:horizontal {\n"
            "background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
            "    stop: 0 #66e, stop: 1 #bbf);\n"
            "background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
            "    stop: 0 #bbf, stop: 1 #55f);\n"
            "border: 1px solid #777;\n"
            "height: 10px;\n"
            "border-radius: 4px;\n"
            "}\n"
            "\n"
            "QSlider::add-page:horizontal {\n"
            "background: #fff;\n"
            "border: 1px solid #777;\n"
            "height: 10px;\n"
            "border-radius: 4px;\n"
            "}\n"
            "\n"
            "QSlider::handle:horizontal {\n"
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
            "    stop:0 #eee, stop:1 #ccc);\n"
            "border: 1px solid #777;\n"
            "width: 13px;\n"
            "margin-top: -2px;\n"
            "margin-bottom: -2px;\n"
            "border-radius: 4px;\n"
            "}\n"
            "\n"
            "QSlider::handle:horizontal:hover {\n"
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
            "    stop:0 #fff, stop:1 #ddd);\n"
            "border: 1px solid #444;\n"
            "border-radius: 4px;\n"
            "}\n"
            "\n"
            "QSlider::sub-page:horizontal:disabled {\n"
            "background: #bbb;\n"
            "border-color: #999;\n"
            "}\n"
            "\n"
            "QSlider::add-page:horizontal:disabled {\n"
            "background: #eee;\n"
            "border-color: #999;\n"
            "}\n"
            "\n"
            "QSlider::handle:horizontal:disabled {\n"
            "background: #eee;\n"
            "border: 1px solid #aaa;\n"
            "border-radius: 4px;\n"
            "}\n"
            "\n"
            "QScrollArea{\n"
            "border: none;\n"
            "}\n"
            "\n"
            "\n"
            ""
        )
        self.mainWidget = QtWidgets.QWidget(parent=MainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftFrame = QtWidgets.QFrame(parent=self.mainWidget)
        self.leftFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.leftFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.leftFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.browseFilesBtn = QtWidgets.QPushButton(parent=self.leftFrame)
        self.browseFilesBtn.setObjectName("browseFilesBtn")
        self.verticalLayout_5.addWidget(self.browseFilesBtn)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_5.addItem(spacerItem)
        self.orignalSignalGB = QtWidgets.QGroupBox(parent=self.leftFrame)
        self.orignalSignalGB.setStyleSheet(
            "QFrame{\n"
            "    background-color: #F0F0F0;\n"
            "    border-radius: 30px;\n"
            "    border: 1px solid rgb(51, 51, 51);\n"
            "}\n"
            "QLabel{\n"
            "    border:none;\n"
            "    font-size: 12px;\n"
            "}\n"
            "QPushButton{\n"
            "  background-color: #333333;\n"
            "  border: none;\n"
            "  border-radius: 19px;\n"
            "  color: #cccccc;\n"
            "  font-size: 14px;\n"
            "  font-weight: 500;\n"
            "  line-height: 19px;\n"
            "  list-style: none;\n"
            "  padding: 4px 4px;\n"
            "\n"
            "}"
        )
        self.orignalSignalGB.setObjectName("orignalSignalGB")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.orignalSignalGB)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.originalSignalFrame = QtWidgets.QFrame(parent=self.orignalSignalGB)
        self.originalSignalFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.originalSignalFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.originalSignalFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.originalSignalFrame.setObjectName("originalSignalFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.originalSignalFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.originalSignalPlayBtn = QtWidgets.QPushButton(
            parent=self.originalSignalFrame
        )
        self.originalSignalPlayBtn.setMinimumSize(QtCore.QSize(40, 0))
        self.originalSignalPlayBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.originalSignalPlayBtn.setObjectName("originalSignalPlayBtn")
        self.horizontalLayout_4.addWidget(self.originalSignalPlayBtn)
        self.originalSignalAtLabel = QtWidgets.QLabel(parent=self.originalSignalFrame)
        self.originalSignalAtLabel.setObjectName("originalSignalAtLabel")
        self.horizontalLayout_4.addWidget(self.originalSignalAtLabel)
        self.originalSignalFromLabel = QtWidgets.QLabel(parent=self.originalSignalFrame)
        self.originalSignalFromLabel.setObjectName("originalSignalFromLabel")
        self.horizontalLayout_4.addWidget(self.originalSignalFromLabel)
        self.originalSignalSoundBtn = QtWidgets.QPushButton(
            parent=self.originalSignalFrame
        )
        self.originalSignalSoundBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.originalSignalSoundBtn.setObjectName("originalSignalSoundBtn")
        self.horizontalLayout_4.addWidget(self.originalSignalSoundBtn)
        self.verticalLayout_3.addWidget(self.originalSignalFrame)
        self.verticalLayout_5.addWidget(self.orignalSignalGB)
        self.updatedSignalGB = QtWidgets.QGroupBox(parent=self.leftFrame)
        self.updatedSignalGB.setStyleSheet(
            "QFrame{\n"
            "    background-color: #F0F0F0;\n"
            "    border-radius: 30px;\n"
            "    border: 1px solid rgb(51, 51, 51);\n"
            "}\n"
            "QLabel{\n"
            "    border:none;\n"
            "    font-size: 12px;\n"
            "}\n"
            "QPushButton{\n"
            "  background-color: #333333;\n"
            "  border: none;\n"
            "  border-radius: 19px;\n"
            "  color: #cccccc;\n"
            "  font-size: 14px;\n"
            "  font-weight: 500;\n"
            "  line-height: 19px;\n"
            "  list-style: none;\n"
            "  padding: 4px 4px;\n"
            "\n"
            "}"
        )
        self.updatedSignalGB.setObjectName("updatedSignalGB")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.updatedSignalGB)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.updatedSignalFrame = QtWidgets.QFrame(parent=self.updatedSignalGB)
        self.updatedSignalFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.updatedSignalFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.updatedSignalFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.updatedSignalFrame.setObjectName("updatedSignalFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.updatedSignalFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.updatedSignalPlayBtn = QtWidgets.QPushButton(
            parent=self.updatedSignalFrame
        )
        self.updatedSignalPlayBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.updatedSignalPlayBtn.setObjectName("updatedSignalPlayBtn")
        self.horizontalLayout_5.addWidget(self.updatedSignalPlayBtn)
        self.updatedSignalAtLabel = QtWidgets.QLabel(parent=self.updatedSignalFrame)
        self.updatedSignalAtLabel.setObjectName("updatedSignalAtLabel")
        self.horizontalLayout_5.addWidget(self.updatedSignalAtLabel)
        self.updatedSignalFromLabel = QtWidgets.QLabel(parent=self.updatedSignalFrame)
        self.updatedSignalFromLabel.setObjectName("updatedSignalFromLabel")
        self.horizontalLayout_5.addWidget(self.updatedSignalFromLabel)
        self.updatedSignalSoundBtn = QtWidgets.QPushButton(
            parent=self.updatedSignalFrame
        )
        self.updatedSignalSoundBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.updatedSignalSoundBtn.setObjectName("updatedSignalSoundBtn")
        self.horizontalLayout_5.addWidget(self.updatedSignalSoundBtn)
        self.verticalLayout_4.addWidget(self.updatedSignalFrame)
        self.verticalLayout_5.addWidget(self.updatedSignalGB)
        self.groupBox = QtWidgets.QGroupBox(parent=self.leftFrame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.selectModeComboBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.selectModeComboBox.setObjectName("selectModeComboBox")
        self.selectModeComboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.selectModeComboBox)
        self.verticalLayout_5.addWidget(self.groupBox)

        self.groupBox2 = QtWidgets.QGroupBox(parent=self.leftFrame)
        self.groupBox2.setObjectName("groupBox2")
        self.horizontalLayoutw_6 = QtWidgets.QHBoxLayout(self.groupBox2)
        self.horizontalLayoutw_6.setObjectName("horizontalLayoutw_6")
        self.selectWindowComboBox = QtWidgets.QComboBox(parent=self.groupBox2)
        self.selectWindowComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.selectWindowComboBox.setObjectName("selectWindowComboBox")
        self.selectWindowComboBox.addItem("")
        self.horizontalLayoutw_6.addWidget(self.selectWindowComboBox)
        self.verticalLayout_5.addWidget(self.groupBox2)
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.leftFrame)
        self.frame_2 = QtWidgets.QFrame(parent=self.mainWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.frame_2)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.topGraphsControllerFrame = QtWidgets.QFrame(parent=self.frame)
        self.topGraphsControllerFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.topGraphsControllerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.topGraphsControllerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topGraphsControllerFrame.setObjectName("topGraphsControllerFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.topGraphsControllerFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playPauseButton = QtWidgets.QPushButton(
            parent=self.topGraphsControllerFrame
        )
        self.playPauseButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("UI\\../../First-Task/UI/icons/play.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.playPauseButton.setIcon(icon)
        self.playPauseButton.setIconSize(QtCore.QSize(30, 30))
        self.playPauseButton.setObjectName("playPauseButton")
        self.horizontalLayout_3.addWidget(self.playPauseButton)
        self.resetButton = QtWidgets.QPushButton(parent=self.topGraphsControllerFrame)
        self.resetButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("UI\\../../First-Task/UI/icons/reset.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.resetButton.setIcon(icon1)
        self.resetButton.setIconSize(QtCore.QSize(30, 30))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_3.addWidget(self.resetButton)
        self.uploadButton = QtWidgets.QPushButton(parent=self.topGraphsControllerFrame)
        self.uploadButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("UI\\../../First-Task/UI/icons/uploadFile.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.uploadButton.setIcon(icon2)
        self.uploadButton.setIconSize(QtCore.QSize(30, 30))
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayout_3.addWidget(self.uploadButton)
        self.zoomInButton = QtWidgets.QPushButton(parent=self.topGraphsControllerFrame)
        self.zoomInButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap("UI\\../../First-Task/UI/icons/zoomIn.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.zoomInButton.setIcon(icon3)
        self.zoomInButton.setIconSize(QtCore.QSize(30, 30))
        self.zoomInButton.setObjectName("zoomInButton")
        self.horizontalLayout_3.addWidget(self.zoomInButton)
        self.zoomOutButton = QtWidgets.QPushButton(parent=self.topGraphsControllerFrame)
        self.zoomOutButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap("UI\\../../First-Task/UI/icons/zoomOut.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.zoomOutButton.setIcon(icon4)
        self.zoomOutButton.setIconSize(QtCore.QSize(30, 30))
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.horizontalLayout_3.addWidget(self.zoomOutButton)
        self.snapshotButton = QtWidgets.QPushButton(
            parent=self.topGraphsControllerFrame
        )
        self.snapshotButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap("UI\\../../First-Task/UI/icons/snapshot.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.snapshotButton.setIcon(icon5)
        self.snapshotButton.setIconSize(QtCore.QSize(30, 30))
        self.snapshotButton.setObjectName("snapshotButton")
        self.horizontalLayout_3.addWidget(self.snapshotButton)
        spacerItem2 = QtWidgets.QSpacerItem(
            170,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_9.addWidget(self.topGraphsControllerFrame)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.leftTopGraph = QtWidgets.QFrame(parent=self.frame_3)
        self.leftTopGraph.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftTopGraph.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftTopGraph.setObjectName("leftTopGraph")
        self.verticalLayout_8.addWidget(self.leftTopGraph)
        self.leftBottomGraph = QtWidgets.QFrame(parent=self.frame_3)
        self.leftBottomGraph.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftBottomGraph.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftBottomGraph.setObjectName("leftBottomGraph")
        self.verticalLayout_8.addWidget(self.leftBottomGraph)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rightTopGraph = QtWidgets.QFrame(parent=self.frame_3)
        self.rightTopGraph.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rightTopGraph.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rightTopGraph.setObjectName("rightTopGraph")
        self.verticalLayout_7.addWidget(self.rightTopGraph)
        self.rightBottomGraph = QtWidgets.QFrame(parent=self.frame_3)
        self.rightBottomGraph.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rightBottomGraph.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rightBottomGraph.setObjectName("rightBottomGraph")
        self.verticalLayout_7.addWidget(self.rightBottomGraph)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.middleTopGraph = QtWidgets.QFrame(parent=self.frame_3)
        self.middleTopGraph.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.middleTopGraph.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.middleTopGraph.setObjectName("middleTopGraph")
        self.verticalLayout_6.addWidget(self.middleTopGraph)
        self.middleBottomGraph = QtWidgets.QFrame(parent=self.frame_3)
        self.middleBottomGraph.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.middleBottomGraph.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.middleBottomGraph.setObjectName("middleBottomGraph")
        self.verticalLayout_6.addWidget(self.middleBottomGraph)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.slidersFrame = QtWidgets.QFrame(parent=self.mainWidget)
        self.slidersFrame.setMinimumSize(QtCore.QSize(0, 200))
        self.slidersFrame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slidersFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.slidersFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.slidersFrame.setObjectName("slidersFrame")
        self.verticalLayout.addWidget(self.slidersFrame)
        MainWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browseFilesBtn.setText(_translate("MainWindow", "Browse Files"))
        self.orignalSignalGB.setTitle(_translate("MainWindow", "Orignal Signal"))
        self.originalSignalPlayBtn.setText(_translate("MainWindow", "p"))
        self.originalSignalAtLabel.setText(_translate("MainWindow", "00"))
        self.originalSignalFromLabel.setText(_translate("MainWindow", "/00"))
        self.originalSignalSoundBtn.setText(_translate("MainWindow", "s"))
        self.updatedSignalGB.setTitle(_translate("MainWindow", "Updated Signal"))
        self.updatedSignalPlayBtn.setText(_translate("MainWindow", "p"))
        self.updatedSignalAtLabel.setText(_translate("MainWindow", "00"))
        self.updatedSignalFromLabel.setText(_translate("MainWindow", "/00"))
        self.updatedSignalSoundBtn.setText(_translate("MainWindow", "s"))
        self.groupBox.setTitle(_translate("MainWindow", "Select Mode"))
        self.groupBox2.setTitle(_translate("MainWindow", "Select Window"))
        self.selectModeComboBox.setItemText(0, _translate("MainWindow", "Uniform"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
